### PR TITLE
Get Travis to do regression testing

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
@anthchirp, I was going to do this, then noticed you had an old branch ready to go and hadn't merged it.  Intentional?

### CODE REVIEW

**Comment by Anthchirp** [comment]
looking at the travis log the most likely scenario is that there was an issue with our builds not working at the time and then I forgot about it.

If the builds pass now this can be merged I believe.

**Comment by benjaminhwilliams** [comment]
Thanks, will do.  I anticipate one test failure (see Jenkins), but I'm fixing that in a separate branch.

**Comment by benjaminhwilliams** [comment]
Hmm... build timeouts during testing.  I'll try longer.

**Comment by Anthchirp** [comment]
Could be that this is waiting on eg. https://github.com/dials/data/issues/33

**Comment by benjaminhwilliams** [comment]
Ah, that would make sense.  And I don't think the 10 min limit is configurable.  The tests themselves should be quite quick, so I imagine you're right and we're just waiting for the data.

**Comment by Anthchirp** [comment]
We won't be doing Travis.

**Pull request closed without merging**
