### PR TITLE
Update calls to dials integration code following refactor

### PR DESCRIPTION
**Pull request by jbeilstenedmands**

### CODE REVIEW

**Comment by Anthchirp** [comment]
I suspect this would break screen19 installations on release versions (DIALS 3.*, but also 2.2.*)

**Comment by ndevenish** [comment]
I've made an attempt at abstracting over the differences in versions, as I don't know anything about the supported DIALS versions for screen19. This now works on master (3.1) and 3.0 in manual testing - the Travis build seems broken for other reasons.

I'm not entirely sure this is error handling properly yet, though - it caught `SystemExit` before, but it looks like `Script.run` didn't explicitly call it anyway - so it might not be catching all of the errors in integration (now, and before, but potentially a different subset now). I'm not sure I'm qualified to make a decision on that here.

**Review by benjaminhwilliams — APPROVED** [review]
Looks good to me, thanks guys.

**Comment by Anthchirp** [comment]
this might fix the tests... let's see

**Comment by benjaminhwilliams** [comment]
That seemed to do the trick, thanks.

**Comment by benjaminhwilliams** [comment]
Just adding a newsfragment...

**Pull request merged**
