### PR TITLE
Retire DIALS 1.14 support

### LINKED ISSUE #23: Remove support for dials 1.x series
Will help the code to be more easily interpreted 🙂

Stumbled across this, thought should record $somewhere

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
When DIALS 1.14 gets EOLed and we are confident no-one is packaging `screen19` with it, retire support for DIALS v < 2.0.

Fixes #23.

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
I left this dormant some time ago but it's probably ready to go if all known popular DIALS distributions are 2.x.

**Comment by benjaminhwilliams** [comment]
Ugh, sorry @Anthchirp, maybe I jumped the gun.  I thought CCP4 7.1 (with DIALS 2.something) had been released, but I now see it hasn't been and CCP4 is still running on DIALS 1.14.

**Comment by benjaminhwilliams** [comment]
Alright, this seems to pass all tests locally on my machine.  Unfortunately, the CI checks are beset by upstream problems.  I've fixed the Python 2 builds.  The remaining Travis failures are a consequence of upstream DIALS build problems (themselves a consequence of https://github.com/cctbx/cctbx_project/issues/487).

It seems unwise to keep this PR open for too much longer as merge conflicts creep in.  I don't think DIALS 1.14 is supported any longer and CCP4 7.1 has been released with DIALS 2.2, so we should be OK to merge this.  I'll hold it for a day or so in case someone addresses the CCTBX issue as it would be nice to see the CI checks succeeding.

**Comment by Anthchirp** [comment]
this still (partially?) retires Python 2 support, eg. removes `from __future__` imports etc.
Is this still intended to be installable on DIALS 2.2+Python 2?

**Comment by benjaminhwilliams** [comment]
Ah yes, good spot, thanks.  I think when I first put this together, I misunderstood the Python 2 support plans to mean that DIALS 2 would be Python 3 only.  I'll reinstate the `from future` imports.  Is there anything else you spotted?  I didn't notice anything else from skimming back over it.

**Pull request merged**
